name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2, 8.3]

    name: PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Install Dependencies
        run: composer install --prefer-dist --classmap-authoritative --no-interaction

      - name: Run Static Analisys
        run: vendor/bin/phpstan analyse --no-progress src

      - name: Run Tests
        run: vendor/bin/pest --no-progress --parallel --coverage-xml=.coverage/xml

      - name: Run Mutation
        run: vendor/bin/pest --no-cache --mutate --parallel
